### PR TITLE
Expose descriptorOf

### PR DESCRIPTION
**Pull request by schell**
Sorry for the deluge of updates, I though this stuff was already in my previous PR.

### CODE REVIEW

**Comment by Twinside** [comment]
I don't see what this pull request brings to the table

**Comment by schell** [comment]
It exposes `descriptorOf` which we talked about in #15. I guess I didn't realize it wasn't re-exported in the top level module.

**Comment by Twinside** [comment]
Ok, I've added the export in a clean commit

**Comment by schell** [comment]
Thank you!

**Pull request closed without merging**
